lsプログラムの作成
shizuka-yamamoto/ruby-practices pull request #6
Opened 2021-08-31 05:47 UTC by shizuka-yamamoto

2021-09-06 09:06 UTC, komagata requested changes

2021-09-06 09:06 UTC, komagata commented on 05.ls/ls.rb
> +if options['l']
`if`の内側にメソッドがあるとコードの実行時の状態によってメソッドが定義されたりされなかったりするようになってしまいます。

特殊な用途でそういうやり方はするかもですが原則やらない方がいいと思います〜

2021-09-06 12:49 UTC, shizuka-yamamoto commented on 05.ls/ls.rb
> +if options['l']
コードレビューをありがとうございます！

コメントを参考に再考しました。
全てのコードをメソッド化し、その中で`if`するプログラムに変更しました。
ご確認をよろしくお願いいたします🙇‍♀️

2021-09-07 14:25 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-07 22:59 UTC, merged